ruby '2.4.0'
source 'https://rubygems.org'

gem 'puma'
gem 'sinatra'
gem 'wavefile'
gem 'oj'
gem 'typhoeus'
gem 'sinatra-asset-pipeline', '0.7.0'
gem 'compass'
gem 'uglifier'
gem 'sass'
gem 'rack-cors', require: 'rack/cors'
gem 'rb-music', '~> 0.0.6'
gem 'fog'
gem 'mime-types'

group :development, :test do
  gem 'foreman'
  gem 'tux'
  gem 'byebug'
  gem 'minitest'
  gem 'rerun'
  gem 'rspec'
  gem 'rubocop'
end
